name: CD

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build & Deploy on Release or Push
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el código
        uses: actions/checkout@v3

      - name: Definir tag para la imagen Docker
        id: get_tag
        run: |
          git fetch --tags
          if [ "${{ github.event_name }}" = "release" ]; then
            tag=$(git describe --tags --abbrev=0 || echo "")
          else
            branch=${GITHUB_REF##*/}
            datetime=$(date +'%Y%m%d%H%M%S')
            tag="${branch}-${datetime}"
          fi
          tag=$(echo "$tag" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9._-' '-')
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Loguearse en DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagen Docker con tag y latest
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/eventhub:${{ steps.get_tag.outputs.tag }} \
            -t ${{ secrets.DOCKER_USERNAME }}/eventhub:latest \
            .

      - name: Subir imágenes a DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/eventhub:${{ steps.get_tag.outputs.tag }}
          docker push ${{ secrets.DOCKER_USERNAME }}/eventhub:latest

      - name: Desplegar en Render
        env:
          DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "$DEPLOY_HOOK" ]; then
            echo "ERROR: El secreto RENDER_DEPLOY_HOOK está vacío o mal definido."
            exit 1
          fi
          echo "Desplegando a Render con el hook:"
          echo "$DEPLOY_HOOK"
          curl -X POST "$DEPLOY_HOOK"
